spring.application.name=lms

spring.data.mongodb.uri=mongodb+srv://eduwatechnologies:qUg7J3dynQsaMuCQ@cluster0.fdpdo18.mongodb.net/lms?retryWrites=true&w=majority
JWT_SECRET=replace_this_with_a_strong_32+_character_key
